# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# TYPO3 extension name of project
EXTENSION: "fire_department"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - "dist/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist:
    typo3: "../Resources/Public"
    dist: "dist"

  # Path to asset folders
  assetTarget:
    typo3: "Build"
    dist: "assets"

  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"

WATCH:
    additionalPaths:
        typo3:
          - "../../public/typo3conf/ext/%EXTENSION%/Configuration/**"
          - "../../public/typo3conf/ext/%EXTENSION%/Resources/Private/**"
    host: www.projectdomain.de.lan
    protocol: https
    # has to be generated with mkcert by yourself before using. Excute following commands here in those folder
    # 1: mkcert -install
    # 2: mkcert "your-domain.ddev.site"
    # Add filenames for key and cert
    ssl:
      key: "certs/replace-filename-here.ddev.site-key.pem"
      cert: "certs/replace-filename-here.ddev.site.pem"

# Add additional sites for proxying when in TYPO3 mode
# You can access them using "yarn run start --typo3 --site=foo"
SITES:
    foo: "bar.projectdomain.de.lan"
